comlab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('maintainance/', views.maintainance_list, name='maintainance'),
    path('lab/', views.lab_view, name='lab'),
    path('teachers/', views.teachers, name='teachers'),
    path('students/', views.students, name='students'),
]

main/models.py
from django.db import models


class Teacher(models.Model):
    satur = 0
    sun = 1
    mon = 2
    tues = 3
    wedns = 4
    thurs = 5
    Choices = [
        (satur, 'السبت'),
        (sun, 'الأحد'),
        (mon, 'الاثنين'),
        (tues, 'الثلاثاء'),
        (wedns, 'الاربعاء'),
        (thurs, 'الخميس')
    ]
    name = models.CharField(max_length=150, verbose_name='الاسم')
    day = models.PositiveSmallIntegerField(
        choices=Choices, verbose_name='يوم المدرس بالمعمل')

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=150, verbose_name='الاسم')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Device(models.Model):
    good = 0
    maintainance = 1
    bad = 2
    Choices = [(good, 'صالح'), (maintainance, 'صيانة'), (bad, 'تالف')]
    state = models.PositiveSmallIntegerField(
        choices=Choices, verbose_name='حالة الجهاز')
    type = models.CharField(max_length=30, verbose_name='نوع الجهاز')

    def __str__(self):
        return self.type


class Maintainance(models.Model):
    company = models.CharField(max_length=150, verbose_name='اسم شركة الصيانة')
    start_date = models.DateField(verbose_name='تاريخ البدء')
    duration = models.PositiveSmallIntegerField(
        verbose_name='مدة أيام الصيانة')

    def __str__(self):
        return 'صيانة من قبل شركة: ' + self.company

main/views.py
from django.shortcuts import render
from .models import Teacher, Student, Device, Maintainance


def index(request):
    return render(request, 'main/index.html')


def maintainance_list(request):
    maintainances = Maintainance.objects.all()
    return render(request, 'main/maintainance.html', {'maintainances': maintainances})

def lab_view(request):
    teachers = Teacher.objects.all().count()
    students = Student.objects.all().count()
    devices = Device.objects.all()
    maintainances = Maintainance.objects.all().count()

    return render(request, 'main/lab.html',
                  {
                      'teachers': teachers,
                      'students': students,
                      'devices': devices,
                      'maintainances': maintainances
                  })

def teachers(request):
    teacher_list = Teacher.objects.all()
    return render(request, 'main/teachers.html', {'teachers': teacher_list})

def students(request):
    student_list = Student.objects.all()
    return render(request, 'main/students.html', {'students': student_list})

templates/main/index.html
<html dir="rtl" lang="ar">
{% block title %}
<title>سجلات معمل الحاسب</title>
{% endblock %}

{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
    integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
    crossorigin="anonymous"></script>

{% block navbar %}
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">الصفحة الرئيسية</a>
    </div>
</nav>
{% endblock %}

{% block header %}
<h1 class="p-5">
    الصفحة الرئيسية
    <br>
    يمكن تصفح القوائم التالية في الموقع:
</h1>
{% endblock %}

{% block content %}
<div class="container px-2">
    <div class="row justify-content-center">
        <div class="py-2 text-center" style="width: 25rem">
            <a href="{% url 'lab' %}" class="btn btn-primary btn-lg py-2" style="width: 25rem">القائمة الرئيسية
                للمعمل</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="py-2" style="width: 25rem">
            <a href="{% url 'teachers' %}" class="btn btn-primary btn-lg py-2" style="width: 25rem">قائمة المعلمين المسجلين
                بالمعمل</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="py-2" style="width: 25rem">
            <a href="{% url 'students' %}" class="btn btn-primary btn-lg py-2" style="width: 25rem">قائمة الطلاب
                المسجلين بالمعمل</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="py-2" style="width: 25rem">
            <a href="{% url 'maintainance' %}" class="btn btn-primary btn-lg py-2" style="width: 25rem">قائمة الصيانات
                بالمعمل</a>
        </div>
    </div>
</div>
{% endblock %}
</div>

</html>

templates/main/lab.html
{% extends "main/index.html" %}
{% load my_filters %}
{% block header %}
<h3 class="p-5">
  عدد المعلمين المسجلين: <a href="{% url 'teachers' %}">{{ teachers }}</a>
  <br>
  عدد الطلاب المسجلين: <a href="{% url 'students' %}">{{ students }}</a>
  <br>
  عدد الصيانات بالمعمل: <a href="{% url 'maintainance' %}">{{ maintainances }}</a>
</h3>
{% endblock %}

{% block content %}
<div class="px-4">
  {% if devices %}
  <h1>جدول أجهزة المعمل:</h1>
  <table class="table table-bordered table-striped table-success" style="width:60rem">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">نوع الجهاز</th>
        <th scope="col">حالة الجهاز</th>
      </tr>
    </thead>
    <tbody>
    {% for device in devices %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ device.type }}</td>
        <td>{{ device.state|get_state }}</td>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h2>لا يوجد جدول بالمعلمين</h2>
  {% endif %}
</div>
{% endblock %}

templates/main/maintainance.html
{% extends "main/lab.html" %}

{% load my_filters %}
{% block header%}
<h2 class="p-5">جدول الصيانات بالمعمل: </h3>
{% endblock %}

{% block content %}
<div class="px-4">
  {% if maintainances %}
  <table class="table table-bordered table-striped table-success" style="width:60rem">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">اسم شركة الصيانة</th>
        <th scope="col">تاريخ بداية الصيانة</th>
        <th scope="col">عدد أيام الصيانة</th>
      </tr>
    </thead>
    <tbody>
    {% for maintainance in maintainances %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ maintainance.company }}</td>
        <td>{{ maintainance.start_date|date:"d/m/Y" }}</td>
        <td>{{ maintainance.duration }}</td>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h2>لا يوجد جدول بالصيانات</h2>
  {% endif %}
</div>
{% endblock %}

templates/main/students.html
{% extends "main/lab.html" %}

{% load my_filters %}
{% block header%}
<h2 class="p-5">جدول الطلاب المسجلين بالمعمل: </h3>
{% endblock %}

{% block content %}
<div class="px-4">
  {% if students %}
  <table class="table table-bordered table-striped table-success" style="width:60rem">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">اسم الطالب</th>
        <th scope="col">معلم الطالب</th>
        <th scope="col">يوم الطالب</th>
      </tr>
    </thead>
    <tbody>
    {% for student in students %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ student.name }}</td>
        <td>{{ student.teacher.name }}</td>
        <td>{{ student.teacher.day|day }}</td>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h2>لا يوجد جدول بالطلاب</h2>
  {% endif %}
</div>
{% endblock %}

templates/main/teachers.html
{% extends "main/lab.html" %}

{% load my_filters %}
{% block header%}
<h2 class="p-5">جدول المعلمين المسجلين بالمعمل: </h3>
{% endblock %}

{% block content %}
<div class="px-4">
  {% if teachers %}
  <table class="table table-bordered table-striped table-success" style="width:60rem">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">اسم الطالب</th>
        <th scope="col">عدد الطلاب المسجلين مع المعلم</th>
        <th scope="col">يوم المعلم</th>
      </tr>
    </thead>
    <tbody>
    {% for teacher in teachers %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ teacher.name }}</td>
        <td>{{ teacher.student_set|count }}</td>
        <td>{{ teacher.day|day }}</td>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h2>لا يوجد جدول بالمعلمين</h2>
  {% endif %}
</div>
{% endblock %}